import Head from "next/head";
import Image from "next/image";
import { Inter, Roboto_Mono, Anton } from "next/font/google";
import styles from "@/styles/Home.module.css";
import bigair from "../../public/bigair.mp4";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Rusto Bigair</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Raleway:wght@100;200;300;600&display=swap"
          rel="stylesheet"
        />
      </Head>
      <section className="relative h-screen flex flex-col items-center justify-center text-center text-white py-0 px-3">
        <div className="video-docker absolute top-0 left-0 w-full h-full overflow-hidden">
          <video
            //controls
            className="min-w-full min-h-full absolute object-cover"
            autoPlay
            muted
            loop
          >
            <source src={bigair} type="video/mp4" />
          </video>
        </div>
        <div className="video-content space-y-2">
          <h1 className="font-light text-6xl">Rusto Bigair</h1>
          <h3 className="font-light text-3xl">07.04.2023</h3>
        </div>
      </section>
    </>
  );
}
